spring.application.name=order-service

server.servlet.context-path=/api/v1
server.port=9011

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/orderDB
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=ALWAYS
spring.sql.init.data-locations=classpath:data.sql
