INSERT INTO product (name, stock, price) VALUES
                                              ('Rolex Submariner Watch', 5, 9500.00),
                                              ('Louis Vuitton Leather Bag', 8, 3200.50),
                                              ('Gucci Sunglasses', 15, 850.75),
                                              ('Hermes Birkin Bag', 2, 12000.00),
                                              ('Prada Designer Shoes', 10, 1400.99),
                                              ('Cartier Diamond Ring', 4, 18000.00),
                                              ('Chanel Perfume Exclusive', 20, 450.00),
                                              ('Burberry Trench Coat', 6, 2200.00),
                                              ('Versace Silk Shirt', 12, 980.25),
                                              ('Armani Luxury Suit', 7, 3000.00),
                                              ('Patek Philippe Watch', 3, 25000.00),
                                              ('Bvlgari Necklace', 5, 11000.00),
                                              ('Dolce & Gabbana Jacket', 9, 1750.40),
                                              ('Fendi Handbag', 6, 2800.60),
                                              ('Balenciaga Sneakers', 14, 1200.00),
                                              ('Tom Ford Sunglasses', 18, 650.30),
                                              ('Montblanc Luxury Pen', 11, 900.00),
                                              ('Yves Saint Laurent Heels', 10, 1300.75),
                                              ('Givenchy Evening Dress', 4, 4500.00),
                                              ('Ralph Lauren Purple Label Suit', 3, 5000.00);